site_name: Cloud Computing 2020
site_description: Course material for the Cloud Computing course of Fall 2020 at the FH Campus Wien.
nav:
  - About the course:
    - Overview: index.md
    - Grading: grading/index.md
    - Project work: projectwork/index.md
    - Deadlines: deadlines/index.md
    - Testing: testing/index.md
    - Getting help: help/index.md
  - Lectures:
    - "Overview": lectures/index.md
    - "1. Introduction to the Cloud": lectures/1-cloud-intro/index.md
    - "2. Infrastructure as a Service": lectures/2-iaas/index.md
    - "3. Beyond IaaS": lectures/3-xaas/index.md
    - "4. Containers": lectures/4-containers/index.md
    - "5. Cloud-native software development": lectures/5-cloud-native/index.md
  - Exercises:
      - Overview: exercises/index.md
      - 1. IaaS: exercises/1-iaas/index.md
      - 2. Terraform: exercises/2-terraform/index.md
      - 3. Containers: exercises/3-containers/index.md
      - 4. Prometheus: exercises/4-prometheus/index.md
      - 5. Grafana: exercises/5-grafana/index.md
      - 6. API integration: exercises/6-api-integration/index.md
  - Glossary:
      - A-Z: glossary/index.md
theme:
  name: material
  features:
    - tabs
  font: false
  logo: logo-wide.svg
  favicon: favicon.svg
  custom_dir: theme
extra_css:
  - custom.css
extra_javascript:
  - player.js
  - external.js
  - download.js
plugins:
  - search
  - macros
  - pdf-export:
      theme_handler_path: pdf-theme-handler.py
      enabled_if_env: ENABLE_PDF_EXPORT
  - exclude:
      glob: []
markdown_extensions:
  - meta
  - admonition
  - markdown_include.include
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
repo_url: https://github.com/fh-cloud-computing/website/
repo_name: "GitHub"
use_directory_urls: true
copyright: Copyright © 2020 Janos Pasztor, Peter Wenzl, Günther Pospischil