site_name: Cloud Computing 2020
nav:
  - About the course:
    - Overview: index.md
    - Grading: grading/index.md
    - Project work: projectwork/index.md
    - Deadlines: deadlines/index.md
    - Testing: testing/index.md
    - Getting help: help/index.md
  - Lectures:
    - Overview: lectures/index.md
    - 1. Introduction to the Cloud: lectures/1-cloud-intro/index.md
    - 2. Cloud capabilities: lectures/2-capabilities/index.md
    - 3. Infrastructure as a Service: lectures/3-iaas/index.md
    - "4. Beyond IaaS: PaaS, SaaS": lectures/4-xaas/index.md
    - 5. Cloud-native software development: lectures/5-cloud-native/index.md
  - Exercises:
      - Overview: exercises/index.md
      - 1. IaaS: exercises/1-iaas/index.md
theme:
  name: material
  custom_dir: theme
  features:
    - tabs
  font:
    text: Verdana
    code: Courier New
  logo: logo-wide.svg
  favicon: favicon.svg
extra_css:
  - custom.css
plugins:
  - search
  - macros
  - mkdocs-simple-hooks:
      hooks:
        on_env: "hooks.on_env:on_env"
  - exclude:
      glob: []
markdown_extensions:
  - meta
  - admonition
  - markdown_include.include
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
repo_url: https://github.com/fh-cloud-computing/website/
repo_name: "GitHub"
use_directory_urls: true
copyright: Copyright © 2020 Janos Pasztor, Peter Wenzl, Günther Pospischil