name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Extract SSH key
        run: |
          mkdir -p ~/.ssh
          chmod 0755 ~/.ssh
          echo "${{secrets.DEPLOY_KEY}}" >~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          path: project
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          path: fh-cloud-computing.github.io
          repository: fh-cloud-computing/fh-cloud-computing.github.io
      - name: Install
        run: |
          pip install -r requirements.txt
        working-directory: project
      - name: Build
        run: mkdocs build
        env:
          ENABLE_PDF_EXPORT: 1
        working-directory: project
      - name: Set remote
        run: |
          git remote set-url origin $(git remote show origin | grep "Fetch URL" | sed -e 's/.*: //' | sed -e 's/https:\/\/github.com\//git@github.com:/')
        working-directory: fh-cloud-computing.github.io
      - name config
        run: "sed -i -e 's/theme_handler_path: pdf-theme-handler.py/theme_handler_path: ..\/project\/pdf-theme-handler.py/' ../project/mkdocs.yml"
        working-directory: fh-cloud-computing.github.io
      - name: deploy
        run: mkdocs gh-deploy --config-file ../project/mkdocs.yml --remote-branch master
        env:
          ENABLE_PDF_EXPORT: 1
        working-directory: fh-cloud-computing.github.io
